name: chat_case_study
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  cloud_firestore: ^3.4.3
  connectivity_plus: ^2.3.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_core: ^1.20.0
  firebase_auth: ^3.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  hydrated_bloc: ^8.1.0
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  rxdart: ^0.27.5
  uuid: ^3.0.6
  firebase_database: ^9.1.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
